<?php

namespace PackratBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ExchangeRate\FixerIoExchangeRateRetriever;
use GuzzleHttp\Client;
use Money\Currency;
use PackratBundle\Entity\ExchangeRate;

/**
 * ExchangeRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRateRepository extends EntityRepository
{
    public function add(Currency $currency)
    {
        $em = $this->getEntityManager();

        $exchangeRate = new ExchangeRate();
        $exchangeRate->setCurrency($currency);

        $em->persist($exchangeRate);
        $em->flush();

        $this->refresh($currency);
    }

    public function addAll()
    {
        $exchangeRate = new FixerIoExchangeRateRetriever(new Client(), new Currency('EUR'));
        $currencies   = $exchangeRate->getAllCurrencies();

        foreach ($currencies as $currency) {
            $this->add($currency['id']);
        }
    }

    /**
     * @param Currency $currency
     */
    public function refresh(Currency $currency)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'UPDATE PackratBundle:ExchangeRate er
                SET er.toEur = :exchangeRate,
                    er.lastUpdated = :now
                WHERE er.currency = :currency'
            )->setParameters([
                'exchangeRate' => $this->getExchangeRateFor($currency),
                'currency'     => $currency,
                'now'          => (new \DateTime())->format('Y-m-d H:i:s'),
            ]);

        $query->execute();
    }

    /**
     * @param Currency[] $currencies
     */
    public function refreshAll(array $currencies)
    {
        foreach ($currencies as $currency) {
            $this->refresh($currency);
        }
    }

    public function addOrRefresh(Currency $currency)
    {
        if ($this->findOneBy(['currency' => $currency]) === null) {
            $this->add($currency);
        } else {
            $this->refresh($currency);
        }
    }

    /**
     * @param Currency $currency
     *
     * @return float
     */
    private function getExchangeRateFor(Currency $currency)
    {
        $exchangeRate = new FixerIoExchangeRateRetriever(new Client(), new Currency('EUR'));

        return $exchangeRate->getFor($currency);
    }
}
