PackratBundle\Entity\Item:
    type: entity
    table: null
    repositoryClass: PackratBundle\Repository\ItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        url:
            type: string
            length: 255
            nullable: true
        imageLocation:
            type: string
            length: 255
            nullable: true
            column: image_location
        status:
            type: string
            length: 255
        currency:
            type: string
            length: 255
            nullable: true
        price:
            type: float
            nullable: true
        priceInEuro:
            type: float
            nullable: true
            column: price_in_euro
        shippingCost:
            type: float
            nullable: true
            column: shipping_cost
        shippingCostInEuro:
            type: float
            nullable: true
            column: shipping_cost_in_euro
        notes:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
