collection_index:
    path:     /
    defaults: { _controller: "PackratBundle:Collection:index" }
    methods:  GET

collection_show:
    path:     /{id}/show
    defaults: { _controller: "PackratBundle:Collection:show" }
    methods:  GET

collection_new:
    path:     /new
    defaults: { _controller: "PackratBundle:Collection:new" }
    methods:  [GET, POST]

collection_edit:
    path:     /{id}/edit
    defaults: { _controller: "PackratBundle:Collection:edit" }
    methods:  [GET, POST]

collection_delete:
    path:     /{id}/delete
    defaults: { _controller: "PackratBundle:Collection:delete" }
    methods:  DELETE
